### ISSUE TITLE
stable-diffusion-webui-forge

### ISSUE THREAD

**Issue by alexbofa** [light-and-ray/sd-webui-cn-in-extras-tab#2]
Hello. please add support to [stable-diffusion-webui-forge](https://github.com/lllyasviel/stable-diffusion-webui-forge)
```cmd
*** Cannot init ControlNet Preprocessor
    Traceback (most recent call last):
      File "C:\Stable-Diffusion-Forge\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 80, in ui
        self.default_unit = get_default_ui_unit()
      File "C:\Stable-Diffusion-Forge\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 65, in get_default_ui_unit
        from scripts.controlnet_ui.controlnet_ui_group import UiControlNetUnit
    ModuleNotFoundError: No module named 'scripts.controlnet_ui'

---
```

**Comment by light-and-ray** [comment]
Forge has completely different cn extension. I tried to make my extension work with it, but it's not possible. I need to rewrite the extension from scratch for forge

**Comment by alexbofa** [comment]
Thanks, I get it. 😔

**Comment by light-and-ray** [comment]
Done! https://github.com/light-and-ray/sd-webui-cn-in-extras-tab/commit/0aaa1b5c642618d5125302e35513fc7643b17d0e
